---
title: "3x3 plots"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
root_path = ''  # change your root_path accordingly
results = readRDS(file.path(root_path, 'data/sim_results/sim_results_all.rds')) %>% bind_rows %>% mutate_at(., c("p","trials"), factor) %>% mutate(., pcorrs = pcorrs*100)
```

```{r}
levels(results$trials) = c("Blocks of 10 trials", "Blocks of 20 trials", "Blocks of 30 trials")
levels(results$p) = c("66%", "75%", "80%")

```


```{r}

maxbeta = 15;
use.p = "75%"

(ggplot(data = filter(results, beta <= maxbeta, p == use.p), mapping = aes(x = alpha, y = beta, fill = pcorrs, z = pcorrs)) + geom_raster(interpolate = TRUE, show.legend = NA)
    + guides(fill = guide_colorbar(barheight = 10))
    + stat_contour(aes(z = pcorrs), color = "black", alpha = 0.5, breaks = seq(0.5,0.90,by = 0.05)*100) 
    + scale_x_continuous(expand = c(0,0), breaks = c(0.25,0.5,0.75,1)) + scale_y_continuous(expand = c(0,0)) 
    + scale_fill_gradient(low = "blue", high = "yellow", limits = c(0.5,0.90)*100, breaks = seq(0.5,0.90,0.05)*100) 
    + xlab(bquote("Learning Rate"~alpha)) + ylab(bquote("Inverse Temperature" ~beta)) 
    + labs(title = "Optimal parameter landscape", subtitle = "Fixed reward probability task", fill = "correct \nchoices \n(%)") 
    + theme(aspect.ratio = 0.75, panel.spacing = unit(0.5, "lines"))
    + facet_grid(. ~ trials)
 
    + geom_point(data = filter(results, beta <= maxbeta, trials == "Blocks of 10 trials", p ==use.p) %>% filter(., pcorrs == max(pcorrs)), mapping = aes(x = alpha, y = beta), shape = 4, size = 1)
    + geom_point(data = filter(results, beta <= maxbeta, trials == "Blocks of 20 trials", p ==use.p) %>% filter(., pcorrs == max(pcorrs)), mapping = aes(x = alpha, y = beta), shape = 4, size = 1)
    + geom_point(data = filter(results, beta <= maxbeta, trials == "Blocks of 30 trials", p ==use.p) %>% filter(., pcorrs == max(pcorrs)), mapping = aes(x = alpha, y = beta), shape = 4, size = 1)
        
 )
    

```

```{r}

# ggsave("fixedp_plot.svg", width = 150, height = 150, units = "mm")

```

```{r}
results.rev = readRDS("sim-results/sim_reversal_all.rds") %>% bind_rows %>% mutate_at(., c("p","reverse_after"), factor) %>% mutate(., pcorrs = pcorrs*100)
```

```{r}
levels(results.rev$reverse_after) = c("Reversal every 10 trials", "Reversal every 30 trials", "Reversal every 50 trials")
levels(results.rev$p) = c("66%", "75%", "80%")

```


```{r}

maxbeta = 15;
use.p = "75%"

(ggplot(data = filter(results.rev, beta <= maxbeta, p == use.p), mapping = aes(x = alpha, y = beta, fill = pcorrs, z = pcorrs)) + geom_raster(interpolate = TRUE, show.legend = NA)
    + guides(fill = guide_colorbar(barheight = 10))
    + stat_contour(mapping = aes(z = pcorrs), color = "black", alpha = 0.5, breaks = seq(0.5,0.90,by = 0.05)*100)
    + scale_x_continuous(expand = c(0,0), breaks = c(0.25,0.5,0.75,1)) + scale_y_continuous(expand = c(0,0)) 
    + scale_fill_gradient(low = "blue", high = "yellow", limits = c(0.49,0.90)*100, breaks = seq(0.5,0.90,0.05)*100) 
    + xlab(bquote("Learning Rate"~alpha)) + ylab(bquote("Inverse Temperature" ~beta)) 
    + labs(title = "", subtitle = "Reversal learning task", fill = "correct \nchoices \n(%)") 
    + theme(aspect.ratio = 0.75, panel.spacing = unit(0.5, "lines"))
    + facet_grid(. ~ reverse_after)
    
    + geom_point(data = filter(results.rev, beta <= maxbeta, reverse_after == "Reversal every 10 trials", p ==use.p) %>% filter(., pcorrs == max(pcorrs)), mapping = aes(x = alpha, y = beta), shape = 4, size = 1)
    + geom_point(data = filter(results.rev, beta <= maxbeta, reverse_after == "Reversal every 30 trials", p ==use.p) %>% filter(., pcorrs == max(pcorrs)), mapping = aes(x = alpha, y = beta), shape = 4, size = 1)
    + geom_point(data = filter(results.rev, beta <= maxbeta, reverse_after == "Reversal every 50 trials", p ==use.p) %>% filter(., pcorrs == max(pcorrs)), mapping = aes(x = alpha, y = beta), shape = 4, size = 1)
)

```


```{r}

# ggsave("reversal_plot.svg", width = 150, height = 150, units = "mm")

```


Line plots

Colors (from light to dark):

#BFD3E6 (191 211 230)
#91ABD1 (145 171 209)
#8C6BB1 (140 107 177)
#810F7C (129  15 124)

```{r, fig.width = 5}

betas = c(1/3, 1,2,5);
trial = "Blocks of 20 trials";
use.p = "75%";

line_d = filter(results, p == use.p, trials == trial, beta %in% betas) %>% mutate(., beta_f = case_when(beta == 1/3 ~ "d", beta == 1 ~ "c", beta == 2 ~ "b", beta == 5 ~"a"))

```

```{r, fig.width = 7, fig.asp = 0.6}

tsize1 = 20
tsize2 = 16

p = ggplot(data = line_d, mapping = aes(x = alpha, y = pcorrs, color = beta_f)) + 
    geom_line(size = 1) + 
    theme_classic() +
    scale_color_manual(values = c("#810F7C","#8C6BB1","#91ABD1","#BFD3E6"), labels = c(expression(tau~bold("= 5")), expression(tau~bold("= 2")), expression(tau~bold("= 1")), expression(tau~bold("= 0.3")))) +
    theme(legend.title = element_blank(), legend.text.align = 0, legend.text = element_text(size = tsize2, face = "bold"), 
          axis.text = element_text(size = tsize2, face = "bold", color = "black"), axis.title = element_text(size = tsize1),
          axis.line = element_line(size = 1), axis.ticks = element_line(size = 1, color = "black"), axis.ticks.length = unit(0.1, "in")) +
    scale_x_continuous(name = expression(bold("Learning rate"~alpha))) + 
    scale_y_continuous(name = expression(bold("Correct choices (%)")), limits = c(50,80))
p
```

```{r}

# ggsave("Plots/lineplot.png", width = 7, height = 7*0.6, unit = "in")

```

